import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  apps: defineTable({
    platform: v.literal("android"),
    packageName: v.string(),
    canonicalPlayStoreUrl: v.string(),
    currentAppName: v.optional(v.string()),
    currentDeveloper: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_platform_package", ["platform", "packageName"]),
  requesters: defineTable({
    name: v.string(),
    email: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }),
  auditRuns: defineTable({
    appId: v.id("apps"),
    requesterId: v.id("requesters"),
    source: v.literal("googlePlay"),
    sourceUrl: v.string(),
    requestedAt: v.number(),
    startedAt: v.optional(v.number()),
    completedAt: v.optional(v.number()),
    status: v.union(v.literal("pending"), v.literal("running"), v.literal("complete"), v.literal("failed")),
    scrapeStatus: v.union(v.literal("pending"), v.literal("running"), v.literal("partial"), v.literal("complete"), v.literal("failed")),
    analysisStatus: v.union(v.literal("pending"), v.literal("running"), v.literal("complete"), v.literal("failed")),
    reviewCount: v.number(),
    usableReviewCount: v.number(),
    skippedReviewCount: v.optional(v.number()),
    lowQualityReviewCount: v.optional(v.number()),
    analysisVersion: v.optional(v.string()),
    scrapeError: v.optional(v.string()),
    scrapeWarning: v.optional(v.string()),
    analysisError: v.optional(v.string()),
    currentStage: v.string(),
    updatedAt: v.number(),
  }).index("by_app_requested_at", ["appId", "requestedAt"]),
  appMetadataSnapshots: defineTable({
    appId: v.id("apps"),
    appName: v.optional(v.string()),
    description: v.optional(v.string()),
    rating: v.optional(v.number()),
    ratingCount: v.optional(v.number()),
    installCount: v.optional(v.string()),
    category: v.optional(v.string()),
    developer: v.optional(v.string()),
    iconUrl: v.optional(v.string()),
    currentVersion: v.optional(v.string()),
    updatedDate: v.optional(v.string()),
    scrapedAt: v.number(),
  }).index("by_app_scraped_at", ["appId", "scrapedAt"]),
  appVersions: defineTable({
    appId: v.id("apps"),
    versionName: v.string(),
    versionCode: v.optional(v.string()),
    releaseDate: v.optional(v.string()),
    firstSeenAt: v.number(),
    lastSeenAt: v.number(),
  }).index("by_app_version", ["appId", "versionName", "versionCode"]),
  reviews: defineTable({
    appId: v.id("apps"),
    source: v.literal("googlePlay"),
    sourceReviewId: v.string(),
    sourceReviewIdKind: v.union(v.literal("native"), v.literal("derived")),
    originalText: v.string(),
    rating: v.number(),
    reviewDate: v.optional(v.string()),
    scrapedAt: v.number(),
    version: v.optional(v.string()),
    qualityStatus: v.union(v.literal("usable"), v.literal("lowQuality")),
  }).index("by_app_source_review", ["appId", "source", "sourceReviewId"]),
  reviewObservations: defineTable({
    auditRunId: v.id("auditRuns"),
    reviewId: v.id("reviews"),
    observedAt: v.number(),
  }).index("by_audit_review", ["auditRunId", "reviewId"]),
  problemCandidates: defineTable({
    appId: v.id("apps"),
    auditRunId: v.id("auditRuns"),
    problemStatement: v.string(),
    evidenceReviewIds: v.array(v.id("reviews")),
    category: v.string(),
    supportingSignalCount: v.number(),
    confidence: v.number(),
    status: v.union(v.literal("accepted"), v.literal("rejected")),
  }).index("by_audit", ["auditRunId"]),
  opportunities: defineTable({
    appId: v.id("apps"),
    auditRunId: v.id("auditRuns"),
    problemStatement: v.string(),
    frequency: v.number(),
    severity: v.number(),
    confidence: v.number(),
    trend: v.number(),
    impact: v.number(),
    priorityScore: v.number(),
    diagnosis: v.string(),
    issueType: v.string(),
    digiaAddressable: v.boolean(),
    recommendedOwner: v.string(),
    lowConfidence: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_audit_score", ["auditRunId", "priorityScore"]),
  evidence: defineTable({
    appId: v.id("apps"),
    auditRunId: v.id("auditRuns"),
    opportunityId: v.id("opportunities"),
    reviewId: v.id("reviews"),
  }).index("by_opportunity", ["opportunityId"]),
  interventions: defineTable({
    appId: v.id("apps"),
    auditRunId: v.id("auditRuns"),
    opportunityId: v.id("opportunities"),
    audience: v.string(),
    trigger: v.string(),
    experienceType: v.string(),
    suggestedCopy: v.string(),
    successMetric: v.string(),
    generationStatus: v.union(v.literal("running"), v.literal("complete"), v.literal("failed")),
    errorMessage: v.optional(v.string()),
    generatedAt: v.number(),
  }).index("by_opportunity", ["opportunityId"]),
  opportunityChanges: defineTable({
    appId: v.id("apps"),
    auditRunId: v.id("auditRuns"),
    opportunityId: v.id("opportunities"),
    field: v.string(),
    previousValue: v.string(),
    nextValue: v.string(),
    changedAt: v.number(),
  }).index("by_opportunity", ["opportunityId"]),
});
